### ISSUE TITLE
Broken in Chrome 63.0.3239.132

### ISSUE THREAD

**Issue by VMBindraban** [moimikey/locale2#61]
In Chrome 63.0.3239.132 the plugin returns `en-gb` while the languages are set on `["nl", "en-GB", "en-US", "en"]`. `en-gb` is OS language while `nl` is the users preferred language.

**Comment by moimikey** [comment]
whoa sorry for the late reply! looking into this...

**Comment by moimikey** [comment]
this should be fixed technically in #62

**Comment by moimikey** [comment]
actually... reopening. this is _not_ fixed yet.

**Comment by moimikey** [comment]
@VMBindraban could you provide some extra detail. on the values you get when you do the following in your console (if applicable):

```
window.navigator.languages
window.navigator.userLanguage
window.clientInformation.language
window.Intl.DateTimeFormat.resolvedOptions().locale
```

also, was this within a chrome app, node, or just in the browser?

**Comment by VMBindraban** [comment]
In the browser (64.0.3282.167 atm).

```
window.navigator.languages => ["nl", "en-US", "en-GB", "en"]
window.navigator.userLanguage => undefined
window.clientInformation.language => "en-GB"
window.Intl.DateTimeFormat.resolvedOptions().locale => Not a function, DateTimeFormat is an function.
```

```
window.navigator.language => "en-GB"
```

**Comment by moimikey** [comment]
@VMBindraban thanks! i made a mistake with the last one:

```
window.Intl.DateTimeFormat().resolvedOptions().locale
```

without being too inquisitive, do you have your mac's language region to Netherlands or UK? I want to clarify what system settings are set and what the browser is then interpreting.

**Comment by VMBindraban** [comment]
```
window.Intl.DateTimeFormat().resolvedOptions().locale => "en-GB"
```

These are my languages in Chrome:

![image](https://user-images.githubusercontent.com/2269400/36414069-35fd84ae-1621-11e8-846e-19956b221eed.png)

And my mac language settings:

![image](https://user-images.githubusercontent.com/2269400/36414124-74d38cc8-1621-11e8-8975-3ba0a78386df.png)

**Comment by VMBindraban** [comment]
Perhaps this also helps, the `window.navigator`:

![image](https://user-images.githubusercontent.com/2269400/36414564-02f5f670-1623-11e8-943d-cdf932c930e2.png)

**Comment by moimikey** [comment]
thanks! will look into a fix for this shortly

**Comment by moimikey** [comment]
sorry this took months :)... i was side-tracked @VMBindraban 

the resolve may be irrelevant by now, but am working on a fix. I assume the result for your case should be: `nl-GB` (correct me if i'm wrong). if you could, i'd love to also see screenshots of your `window.navigator` in firefox and safari as well if you could. thanks

**Comment by VMBindraban** [comment]
I am not using this module anymore but i can at least provide you with the info to fix it. :)

Safari 11.1.2:

![image](https://user-images.githubusercontent.com/2269400/43703678-d2da77d6-995d-11e8-8a69-2f5cec3b317d.png)

Firefox 61.0.1:

![image](https://user-images.githubusercontent.com/2269400/43703752-1666d580-995e-11e8-9536-08e5d023ed83.png)

**Comment by VMBindraban** [comment]
I think Chrome fixed the issue somewhere between version 63 and 67.

This is 67.0.3:
![image](https://user-images.githubusercontent.com/2269400/43703866-6156a19c-995e-11e8-8e15-3c1b700c2027.png)

**Comment by moimikey** [comment]
thanks @VMBindraban! (that's interesting re: chrome)
