### ISSUE TITLE
chrome.app.getDetails() is deprecated

### ISSUE THREAD

**Issue by paulirish** [moimikey/locale2#63]
https://developer.chrome.com/extensions/runtime#method-getManifest is recommended instead. It returns an identical object, anyway.

![image](https://user-images.githubusercontent.com/39191/43917473-4a89eec4-9bc5-11e8-83ef-3b9e159bbb41.png)

**Comment by moimikey** [comment]
much thanks Mr.Irish 😄 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
